### PR TITLE
inline public key handling for the 0.12.x line

### PR DESCRIPTION
**Pull request by tobowers**
This engaging PR falls hot on the heels of other PRs you have come to love like #101 .

Brings inline crypto public key handling to the 0.12.x branch as it is in the master branch.

### CODE REVIEW

**Comment by tobowers** [comment]
fixed linting again

**Comment by vasco-santos** [comment]
Just remove this line, we removed the commitlint from CI:

https://github.com/libp2p/js-peer-id/blob/0.12.x/.travis.yml#L25

**Comment by tobowers** [comment]
done.

**Comment by vasco-santos** [comment]
Thanks @tobowers !

I am releasing everything shortly

**Comment by vasco-santos** [comment]
Shipped `0.12.5` with this

**Comment by tobowers** [comment]
thank you!

**Pull request merged**
