### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by achingbrain**
Updates deps to the latest versions to dedupe the dep tree.

### CODE REVIEW

**Comment by vasco-santos** [comment]
Pushed `util` dev dependency to get the browser build running

**Comment by achingbrain** [comment]
That's weird, `web-encoding@1.1.4` has `util` as a dependency so it shouldn't be necessary.  Could there have been an older version cached on Travis?

**Comment by vasco-santos** [comment]
@achingbrain you seem right about caching. I reverted the commit and also tried it locally.
Somehow, I can restart the PR job though...

**Review by vasco-santos — APPROVED** [review]
LGTM

**Pull request merged**
