### PR TITLE
feat: adds typescript types + type tests

### PR DESCRIPTION
**Pull request by carsonfarmer**
Depends on https://github.com/multiformats/js-cid/pull/102 for tests to run/work nicely, but this PR is already useful on its own if you don't want to use the tests in CI etc.

### CODE REVIEW

**Comment by carsonfarmer** [comment]
Keeping this as a draft for now, until multiformats/js-cid#102 is (hopefully merged and) released (tho this PR is already useful as is). If you'd rather _not_ have these types in this repo, please let me know @vasco-santos, and I can PR them to definitelytyped instead.

**Comment by carsonfarmer** [comment]
See https://github.com/libp2p/js-libp2p-crypto/pull/161 for a discussion of the possible applications of these types for CI etc.

**Comment by carsonfarmer** [comment]
Type checking/tests could be added to CI by adding:

```
    - stage: types
      script:
        - npm run test:types
```

**Comment by carsonfarmer** [comment]
Awesome, any chance we could get a patch release once this is merged 🙏?

P.S. I will indeed ping you if/when I get a chance to update `js-multicodec` 👍.

**Comment by hacdias** [comment]
@carsonfarmer thanks. Pinging @vasco-santos since I don't have publish permissions here.

**Comment by jacobheun** [comment]
Released in 0.13.7.

**Pull request merged**
